## Data Exploration of Credit Data

In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import re

In [2]:
df = pd.read_csv('credit-training.csv')

In [3]:
df.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 11 columns):
SeriousDlqin2yrs                        150000 non-null int64
RevolvingUtilizationOfUnsecuredLines    150000 non-null float64
age                                     150000 non-null int64
NumberOfTime30-59DaysPastDueNotWorse    150000 non-null int64
DebtRatio                               150000 non-null float64
MonthlyIncome                           120269 non-null float64
NumberOfOpenCreditLinesAndLoans         150000 non-null int64
NumberOfTimes90DaysLate                 150000 non-null int64
NumberRealEstateLoansOrLines            150000 non-null int64
NumberOfTime60-89DaysPastDueNotWorse    150000 non-null int64
NumberOfDependents                      146076 non-null float64
dtypes: float64(4), int64(7)
memory usage: 12.6 MB

In [8]:
df.columns

Index([u'SeriousDlqin2yrs', u'RevolvingUtilizationOfUnsecuredLines', u'age',
       u'NumberOfTime30-59DaysPastDueNotWorse', u'DebtRatio', u'MonthlyIncome',
       u'NumberOfOpenCreditLinesAndLoans', u'NumberOfTimes90DaysLate',
       u'NumberRealEstateLoansOrLines',
       u'NumberOfTime60-89DaysPastDueNotWorse', u'NumberOfDependents'],
      dtype='object')

In [16]:
for column in df.columns:
    print column, sum(df[column].isnull())

 SeriousDlqin2yrs 0
RevolvingUtilizationOfUnsecuredLines 0
age 0
NumberOfTime30-59DaysPastDueNotWorse 0
DebtRatio 0
MonthlyIncome 29731
NumberOfOpenCreditLinesAndLoans 0
NumberOfTimes90DaysLate 0
NumberRealEstateLoansOrLines 0
NumberOfTime60-89DaysPastDueNotWorse 0
NumberOfDependents 3924

In [18]:
df.isnull().sum()

SeriousDlqin2yrs                            0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome                           29731
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3924
dtype: int64

In [30]:
def snakify(text):
    return text.replace(" ","_").lower()

for column in df.columns:
    print snakify(column)

seriousdlqin2yrs
revolvingutilizationofunsecuredlines
age
numberoftime30-59dayspastduenotworse
debtratio
monthlyincome
numberofopencreditlinesandloans
numberoftimes90dayslate
numberrealestateloansorlines
numberoftime60-89dayspastduenotworse
numberofdependents

** No spaces between phrases in column names **

In [50]:
df.describe()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000
mean,0.066840,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222
std,0.249746,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,0.000000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [20]:
df['age'][df['age'] > 34].count()

130760

In [21]:
df['SeriousDlqin2yrs'][df['SeriousDlqin2yrs'] == 0].count()

139974

In [24]:
df['NumberOfOpenCreditLinesAndLoans'][df['NumberOfOpenCreditLinesAndLoans'] < 10].count()

97366

In [41]:
df[(df['age'] > 34) & (df['SeriousDlqin2yrs'] == 0) & (df['NumberOfOpenCreditLinesAndLoans'] < 10)]

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
5,0,0.213179,74,0,0.375607,3500.0,3,0,1,0,1.0
6,0,0.305682,57,0,5710.000000,NaN,8,0,3,0,0.0
7,0,0.754464,39,0,0.209940,3500.0,8,0,0,0,0.0
9,0,0.189169,57,0,0.606291,23684.0,9,0,4,0,2.0
11,0,0.018798,51,0,0.531529,6501.0,7,0,2,0,2.0
14,0,0.019657,76,0,477.000000,0.0,6,0,1,0,0.0
15,0,0.548458,64,0,0.209892,11362.0,7,0,1,0,2.0
17,0,0.166284,53,0,0.188274,8800.0,7,0,0,0,0.0
18,0,0.221813,43,0,0.527888,3280.0,7,0,1,0,2.0
22,0,1.000000,39,0,0.241104,2500.0,4,0,0,0,0.0
24,0,0.046560,58,0,0.241622,2416.0,9,0,1,0,0.0
32,0,0.083418,62,0,977.000000,NaN,6,0,1,0,0.0
33,0,0.186869,57,0,0.313812,7000.0,9,0,2,0,0.0
34,0,0.693330,42,2,0.257732,2230.0,7,0,0,0,0.0
35,0,0.000000,64,0,0.073539,11000.0,9,0,1,0,0.0
36,0,0.881836,50,3,0.567858,4000.0,9,0,1,0,1.0
37,0,1.000000,75,1,0.134078,3400.0,1,0,1,0,1.0
41,0,0.072898,81,0,75.000000,NaN,7,0,0,0,0.0
46,0,0.061440,62,0,0.011168,3133.0,2,0,0,0,0.0
50,0,0.818978,73,0,3095.000000,0.0,9,0,1,1,0.0
52,0,1.000000,62,0,0.000000,NaN,1,0,0,0,0.0
53,0,0.028562,51,0,0.306381,5750.0,5,0,1,0,0.0
55,0,0.070854,55,0,0.073148,13793.0,4,0,1,0,0.0
57,0,0.401200,64,0,0.351259,3216.0,4,0,1,0,0.0
58,0,0.541109,43,0,2477.000000,NaN,3,0,1,0,2.0
61,0,0.027400,69,0,0.008034,5600.0,3,0,0,0,0.0
63,0,0.009789,46,0,1.051398,3326.0,6,0,2,0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
149936,0,0.326193,66,0,0.407591,2423.0,5,0,0,0,0.0
149938,0,0.329479,35,1,0.339813,2571.0,7,0,1,0,1.0
149942,0,0.208187,60,0,0.386186,9106.0,9,0,2,0,1.0
149946,0,0.923845,38,0,21.000000,NaN,2,0,0,0,0.0
149951,0,0.014510,76,0,0.143180,3100.0,8,0,0,0,0.0
149952,0,0.019785,58,0,1328.000000,NaN,6,0,1,0,2.0
149953,0,0.231488,41,0,1198.000000,NaN,3,0,1,0,0.0
149958,0,0.457101,63,0,4945.000000,NaN,9,0,1,0,0.0
149959,0,0.293143,67,0,0.224866,9916.0,4,0,1,0,0.0
149960,0,0.000000,49,0,353.000000,NaN,2,0,0,0,0.0
149962,0,1.005733,48,0,0.248896,2944.0,4,3,0,0,1.0
149964,0,1.010934,63,0,0.608211,6015.0,8,0,1,0,0.0
149967,0,0.977899,63,0,517.000000,NaN,5,0,0,1,0.0
149970,0,0.025449,58,0,0.253855,15500.0,7,0,2,0,2.0
149971,0,0.058001,83,0,0.013997,5000.0,6,0,0,0,0.0
149972,0,0.071273,42,0,0.008638,6945.0,3,0,0,0,1.0
149973,0,1.026395,44,0,0.494819,5500.0,7,0,1,0,1.0
149975,0,0.022088,58,0,2716.000000,NaN,8,0,2,0,0.0
149976,0,0.000627,76,0,60.000000,NaN,5,0,0,0,0.0
149978,0,0.917635,52,2,0.259496,2500.0,4,0,0,0,0.0
149981,0,0.810012,43,0,0.121752,6849.0,4,0,0,0,4.0
149982,0,0.021046,37,0,0.250272,2760.0,8,0,0,0,3.0
149983,0,0.002485,82,0,0.000800,5000.0,5,0,0,0,0.0
149984,0,0.037548,84,0,25.000000,NaN,5,0,0,0,0.0
149989,0,0.013356,62,0,0.001408,9233.0,4,0,0,0,3.0
149990,0,0.055518,46,0,0.609779,4335.0,7,0,1,0,2.0
149994,0,0.385742,50,0,0.404293,3400.0,7,0,0,0,0.0
149995,0,0.040674,74,0,0.225131,2100.0,4,0,1,0,0.0
149996,0,0.299745,44,0,0.716562,5584.0,4,0,1,0,2.0
149999,0,0.850283,64,0,0.249908,8158.0,8,0,2,0,0.0

In [25]:
df['SeriousDlqin2yrs'][df['SeriousDlqin2yrs'] == 1].count()

10026

In [48]:
ninetieth = df['MonthlyIncome'].quantile(0.9)
df['MonthlyIncome'][df['MonthlyIncome'] >= ninetieth].count()

12061

In [49]:
df[(df['SeriousDlqin2yrs'] == 1) & (df['MonthlyIncome'] >= ninetieth)]

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
13,1,0.964673,40,3,0.382965,13700.0,9,3,1,1,2.0
334,1,0.037198,47,0,0.039758,25000.0,11,0,1,0,3.0
350,1,0.635721,68,1,0.218071,25000.0,27,0,3,0,0.0
642,1,0.402346,37,0,0.337622,12667.0,16,0,2,0,3.0
653,1,0.314686,51,3,0.160318,16984.0,13,0,2,1,4.0
1339,1,0.409985,69,1,0.279981,14600.0,15,0,2,0,0.0
1404,1,0.000000,67,0,0.345825,16383.0,20,0,3,0,1.0
1464,1,0.702381,54,0,0.866733,14166.0,21,0,6,0,3.0
1648,1,0.922506,45,0,0.501614,12700.0,11,0,4,0,1.0
2081,1,0.772891,55,2,0.286726,12000.0,6,1,2,0,0.0
2495,1,0.451376,48,0,2.511961,12080.0,29,0,17,0,2.0
2823,1,0.071555,30,0,0.234655,19500.0,11,0,3,0,0.0
3051,1,0.123953,54,2,0.969926,13100.0,24,0,6,0,4.0
3110,1,1.000000,49,0,0.204984,13000.0,2,3,1,2,1.0
3710,1,0.845686,52,1,0.257959,25600.0,9,0,3,0,0.0
3815,1,0.451073,51,0,0.265251,12523.0,11,0,2,0,3.0
5353,1,0.043153,65,0,0.193548,14166.0,16,0,2,0,0.0
5749,1,0.538074,53,0,0.406380,20000.0,9,0,1,1,1.0
5848,1,0.962703,54,1,0.169832,13583.0,15,2,0,1,0.0
5918,1,0.648226,34,0,0.270639,12100.0,12,0,2,0,0.0
6658,1,0.804867,31,2,0.005642,81000.0,5,0,0,0,2.0
7355,1,0.907706,45,1,0.360046,19166.0,15,0,2,0,2.0
7534,1,0.178821,51,0,0.185401,12000.0,18,0,1,0,1.0
7535,1,0.000000,47,0,0.136357,29583.0,8,0,2,0,4.0
7650,1,0.998625,48,1,0.137596,14200.0,4,3,0,2,3.0
7991,1,0.996631,54,2,0.679430,24000.0,16,0,5,0,0.0
8230,1,0.943343,52,0,0.264789,25000.0,7,0,0,1,3.0
8422,1,1.008796,33,3,0.182321,15000.0,11,0,2,0,2.0
8687,1,0.548518,51,2,0.333422,18750.0,11,0,2,0,2.0
8863,1,0.823918,67,0,0.155658,18000.0,6,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
142222,1,0.333434,58,0,0.093646,101167.0,19,0,7,0,0.0
142390,1,0.507885,43,2,0.427681,17000.0,14,0,3,0,2.0
142765,1,0.087587,37,0,0.370493,16666.0,22,0,3,0,0.0
142797,1,0.261885,44,0,0.351566,32633.0,10,0,3,0,3.0
142894,1,0.782628,49,0,0.234640,21500.0,11,0,1,0,2.0
143009,1,0.073525,45,0,0.485349,13445.0,8,0,4,0,1.0
143172,1,0.592267,38,0,0.458188,13500.0,13,0,4,0,3.0
143669,1,1.079904,38,4,0.374304,11666.0,9,0,2,2,3.0
143742,1,0.009300,58,0,0.065789,18467.0,7,0,2,0,2.0
144013,1,0.758419,45,4,0.350393,16666.0,6,2,2,2,1.0
144479,1,0.078785,66,1,0.158993,14421.0,17,0,0,0,1.0
144592,1,0.134779,57,0,0.170790,12166.0,8,0,2,1,0.0
144701,1,0.199084,39,1,0.562595,12500.0,8,0,4,0,1.0
144924,1,0.194812,39,2,0.368755,26000.0,14,0,4,0,2.0
145210,1,0.000141,34,0,0.150714,18000.0,14,1,1,0,3.0
145594,1,0.138129,40,0,0.455682,14000.0,16,0,3,0,0.0
145632,1,0.938027,41,1,0.614992,14900.0,20,0,10,0,1.0
145900,1,0.740519,40,1,0.153105,12977.0,5,0,1,0,0.0
146187,1,0.057206,56,0,0.493456,13218.0,10,0,5,0,1.0
147304,1,3.278989,59,0,0.347268,12007.0,15,1,2,0,0.0
147531,1,1.020396,61,0,0.166569,15332.0,6,2,1,2,1.0
147939,1,0.709265,53,4,0.306926,14250.0,18,1,1,0,2.0
147964,1,0.679605,58,0,0.587470,15833.0,20,0,5,0,1.0
148107,1,1.000000,55,0,0.351974,12159.0,3,2,1,0,0.0
148194,1,0.509778,43,0,0.318694,13228.0,7,0,2,0,2.0
148261,1,0.025302,39,0,0.285174,50000.0,15,0,5,0,2.0
148684,1,0.950171,62,3,0.548105,14166.0,14,0,1,2,1.0
149168,1,1.034183,51,1,0.251655,12083.0,3,0,1,1,1.0
149481,1,0.873251,44,0,0.021001,51140.0,7,2,1,0,3.0
149937,1,0.677345,38,3,0.242278,13500.0,9,0,1,0,3.0